### ISSUE TITLE
increase accessibility by including measurements in-context

### ISSUE THREAD

**Issue by FekketCantenel** [isaacvando/cookrender#2]
I'm learning to cook and have a short attention span, so I'm experimenting with [recipe accessibility](https://medium.com/illumination/written-recipes-arent-adhd-friendly-791bc2147ad1). The cooklang spec and your rendering tool have been invaluable so far.

The [Easy Read Recipes format](https://www.easyreadrecipes.com/sample-recipe/) is the most accessible that I've found so far. Rendering this with Markdown would be difficult because 1) you'd have to rewrite the steps portion, and 2) two columns would require a table, which might complicate rendering.

A compromise is (the option) to include measurements when rendering steps. For example, this is the current rendering:

```
- In a separate bowl, use the measuring spoon and a **measuring cup** to measure
out **matzo meal**, **baking powder**, **garlic powder**...
```

In practice, matching each ingredient to the measurement in a separate list is tedious. It would make a big difference if, in addition to the ingredients list, measurements could optionally be rendered like so:

```
- In a separate bowl, use the measuring spoon and a **measuring cup** to measure
out **¾ cup matzo meal**, **1 tsp baking powder**, **½ tsp garlic powder**...
```

**Comment by isaacvando** [comment]
This is a good idea. I will add it as an optional setting because I imagine some people would prefer to not have the quantities listed in the instructions. I should be able to do it in the next few days.

**Comment by isaacvando** [comment]
This feature is now live. By default it is turned off but you just need to set `"cookrender.enableInlineQuantities": true`.

**Comment by FekketCantenel** [comment]
Thanks so much for this and the numbered steps! These provide an immediate improvement to usability.

This is a nitpick: I don't think numbering the equipment inline is useful, and instead adds clutter. Here's how the above now renders:

```
3. In a separate bowl, use the measuring spoon and a **measuring cup (1)** to measure
out **matzo meal (¾ cup)**, **baking powder (1 tsp)**, **garlic powder (½ tsp)**...
```

**Comment by isaacvando** [comment]
That's a good point. A new version with separate settings for cookware and ingredients is live now!

**Comment by FekketCantenel** [comment]
Thank you! I was going to suggest adding these options to the documentation, but you've already updated the main readme. You're good at this!
