### ISSUE TITLE
number steps

### ISSUE THREAD

**Issue by FekketCantenel** [isaacvando/cookrender#3]
(This might win 'tiniest nitpick'! Apologies in advance.)

Currently, steps are rendered as non-numbered bullet-points (`-`). Numbering steps has several benefits:

1. If steps have been broken down properly, the number of steps provides an at-a-glance estimate of how complicated and involved a recipe is.
2. One can refer to 'step X' within the recipe, or mark one's place in a longer recipe.

When rendering steps, the number might be auto-incremented. I believe Markdown also supports just starting each item with `1.` and praying that a given renderer will auto-increment.

**Comment by isaacvando** [comment]
Sounds good to me! I can do it this week.
