### ISSUE TITLE
Enable Rendering fails with absolute file paths

### ISSUE THREAD

**Issue by ElementCy** [isaacvando/cookrender#5]
I tested with a simple .cook file in a directory at the root of my secondary harddrive, ie 

> "D:\Test Cook\Test Recipe.cook"

When I run command to enable rendering, the popup shows that it is enabled, but no markdown file is created. Looking at the extension logs, I was getting the following:

> Error (FileSystemError): Unable to resolve filesystem provider with relative file path "d:\Test Cook\Test Recipe.md"

I think vscode.Uri.parse doesn't work well with absolute pathing, and switching it to vscode.Uri.file worked for me. I'm not sure if that is the right solution to do, as this was just me googling the vscode extension api docs for a few minutes.

**Comment by isaacvando** [comment]
Thanks for pointing this out! I'm glad to know the difference now.

I changed the code to use vscode.Uri.file but I don't have a Windows machine to test it so please let me know if that fix solves your issue. The changes are live now.

**Comment by ElementCy** [comment]
Created just fine for me now. Thanks.
